# 내적

- 백터의 길이
- 벡터 사이의 관계

In [2]:
import numpy as np

In [3]:
#9.5.1 : 기본내적 실습

a = [1, 2, 3]
b = [4, 5, 6]
n = len(a)
result = 0 # 내적의 결과를 저장할 변수
for i in range(n):
    result += a[i] * b[i]
print(result)

32


In [4]:
def inner_product(a, b):
    '''
    벡터의 내적
    입력값: 내적할 두 벡터 리스트 a, b
    출력값: 내적의 결과
    a와 b는 같은 길이의 리스트여야 한다.
    내적은 두 벡터의 같은 인덱스의 원소를 곱한 후 모두 더한 값이다.
    '''
    n = len(a)
    result = 0 # 내적의 결과를 저장할 변수
    for i in range(n):
        result += a[i] * b[i]
    return result

print(inner_product(a, b))
print(inner_product([1, 2], [4, 5]))

32
14


In [29]:
# 9.5.2 : 그램 슈미트 과정을 이용한 QR 분해

A = [[1,0,1],[0,1,1],[1,2,0]]

n = len(A) # 행렬 A의 행의 개수
p = len(A[0]) # 행렬 A의 열의 개수
a1 = [] # 행렬 A의 1열에 해당하는 열벡터
a2 = [] # 행렬 A의 2열에 해당하는 열벡터
a3 = [] # 행렬 A의 3열에 해당하는 열벡터

# 행렬 A의 열벡터 분해
for i in range(n):
    a1.append(A[i][0])
    a2.append(A[i][1])
    a3.append(A[i][2])

In [30]:
# # 행렬 A의 열벡터 분해 확인
print(a1);print(a2);print(a3)

[1, 0, 1]
[0, 1, 2]
[1, 1, 0]


In [38]:
# 벡터 u1구하기

u1 = a1
print(u1)

# 벡터 u2구하기
scalar = inner_product(a2, u1) / inner_product(u1, u1)
u2 = [a2[i] - scalar * u1[i] for i in range(len(a2))]
print(u2)

# 벡터 u3구하기
scalar = inner_product(a3, u1) / inner_product(u1, u1)
u3 = [a3[i] - scalar * u1[i] for i in range(len(a3))]
print(u3)

[1, 0, 1]
[-1.0, 1.0, 1.0]
[0.5, 1.0, -0.5]


### 벡터 u2 구하기

$$
\mathbf{u}_2 = \mathbf{a}_2 - \frac{\langle \mathbf{a}_2, \mathbf{u}_1 \rangle}{\|\mathbf{u}_1\|^2} \mathbf{u}_1
$$

- a2 와 u1의 내적값
- 벡터 u1의 norm(길이)의 제곱값

In [37]:
u1 = a1

# a2 와 u1의 내적값
dp21 = 0 # a2와 u1의 내적값 초기값 선언
for i in range(0, len(u1)): # a2와 u1의 i번째 원소에 대해
    temp = a2[i] * u1[i] # a2와 u1의 i번째 원소를 곱한 후 temp에 저장
    dp21 += temp # dp21에 각 벡터의 원소의 곱 temp를 더함
print(dp21)


# 벡터 u1의 길이인 norm 구하기
norm_u1 = 0 # norm_u1 초기값 선언
for i in range(0, len(u1)): # u1의 i번째 원소에 대해
    norm_u1 += u1[i]**2 # u1의 i번째 원소를 제곱한 후 norm_u1에 저장
norm_u1 = norm_u1**0.5 # norm_u1을 제곱근으로 변환
print(norm_u1) # norm_u1을 제곱근으로 변환하여 출력

# u2 벡터 구하기
u2 = [a2[i] - (dp21 / norm_u1**2) * u1[i] for i in range(len(a2))]
print(u2)


2
1.4142135623730951
[-0.9999999999999998, 1.0, 1.0000000000000002]


### 벡터 u3 구하기


$$
\mathbf{u}_3 = \mathbf{a}_3 - \frac{\langle \mathbf{a}_3, \mathbf{u}_1 \rangle}{\|\mathbf{u}_1\|^2} \mathbf{u}_1 - \frac{\langle \mathbf{a}_3, \mathbf{u}_2 \rangle}{\|\mathbf{u}_2\|^2} \mathbf{u}_2
$$

- a3 와 u1의 내적값, a3 와 u2의 내적값
- 벡터 u1과 벡터 u2의 norm(길이)의 제곱값

In [46]:
u1 = a1
print(u1)
print(a3)
print(u2)
print(a3)


[1, 0, 1]
[1, 1, 0]
[-1.0, 1.0, 1.0]
[1, 1, 0]


In [48]:
# a3와 u1의 내적값
dp31 = 0 # a3와 u1의 내적값 초기값 선언
for i in range(0, len(u1)): # a3와 u1의 i번째 원소에 대해
    temp = a3[i] * u1[i] # a3와 u1의 i번째 원소를 곱한 후 temp에 저장
    dp31 += temp # dp31에 각 벡터의 원소의 곱 temp를 더함
    # print(i, temp, dp31)
print(dp31)

# a3와 u2의 내적값
dp32 = 0 # a3와 u2의 내적값 초기값 선언
for i in range(0, len(u2)): # a3와 u2의 i번째 원소에 대해
    temp = a3[i] * u2[i] # a3와 u2의 i번째 원소를 곱한 후 temp에 저장
    dp32 += temp # dp32에 각 벡터의 원소의 곱 temp를 더함
    # print(i, temp, dp32)
print(dp32)

# 벡터 u2의 길이인 norm_u2 구하기
norm_u2 = 0 # norm_u2 초기값 선언
for i in range(0, len(u2)): # u2의 i번째 원소에 대해
    norm_u2 += u2[i]**2 # u2의 i번째 원소를 제곱한 후 norm_u2에 저장
norm_u2 = norm_u2**0.5 # norm_u2을 제곱근으로 변환
print(norm_u2) # norm_u2을 제곱근으로 변환하여 출력

1
0.0
1.7320508075688772


In [49]:
# u3 벡터 구하기
u3 = [a3[i] - (dp31 / norm_u1**2) * u1[i] - (dp32 / norm_u2**2) * u2[i] for i in range(len(a3))]
print(u3)

[0.5000000000000001, 1.0, -0.4999999999999999]


In [50]:
# u3의 길이 구하기
norm_u3 = 0 # norm_u3 초기값 선언
for i in range(0, len(u3)): # u3의 i번째 원소에 대해
    norm_u3 += u3[i]**2 # u3의 i번째 원소를 제곱한 후 norm_u3에 저장
norm_u3 = norm_u3**0.5 # norm_u3을 제곱근으로 변환
print(norm_u3) # norm_u3을 제곱근으로 변환하여 출력

1.224744871391589


### 정규 직교 벡터


$$
\mathbf{v}_1 = \frac{1}{\|\mathbf{u}_1\|} \mathbf{u}_1
$$

$$
\mathbf{v}_2 = \frac{1}{\|\mathbf{u}_2\|} \mathbf{u}_2
$$

$$
\mathbf{v}_3 = \frac{1}{\|\mathbf{u}_3\|} \mathbf{u}_3
$$

In [52]:
# 정규 직교 벡터 구하기
v1 = [u1[i] / norm_u1 for i in range(len(u1))]
v2 = [u2[i] / norm_u2 for i in range(len(u2))]
v3 = [u3[i] / norm_u3 for i in range(len(u3))]
print(v1)   
print(v2)
print(v3)

[0.7071067811865475, 0.0, 0.7071067811865475]
[-0.5773502691896258, 0.5773502691896258, 0.5773502691896258]
[0.40824829046386313, 0.8164965809277261, -0.40824829046386296]


## QR 분해

A = QR ; 행렮 A의 열벡터끼리 모두 선형독립일 때, 크기 큰 행렬의 고유값 구할 때 씀

- Q : nxp 행렬, 정규직교벡터
- R : 가역상삼각행렬

In [53]:
# 행렬 Q 구하기
Q = np.zeros((n, p)) # 행렬 Q 초기화
for i in range(n): # 행렬 Q의 i번째 행에 대해
    Q[i][0] = v1[i] # 행렬 Q의 i번째 행의 0번째 열에 v1을 저장
    Q[i][1] = v2[i] # 행렬 Q의 i번째 행의 1번째 열에 v2을 저장
    Q[i][2] = v3[i] # 행렬 Q의 i번째 행의 2번째 열에 v3을 저장
print(Q) # 행렬 Q 출력

[[ 0.70710678 -0.57735027  0.40824829]
 [ 0.          0.57735027  0.81649658]
 [ 0.70710678  0.57735027 -0.40824829]]


In [58]:
# 행렬 R 구하기
R = np.zeros((p, p)) # 행렬 R 초기화

for i in range(p): # 행렬 R의 i번째 행에 대해
    R[0][0] += a1[i]*v1[i] 
    R[0][1] += a2[i]*v1[i] 
    R[0][2] += a3[i]*v1[i] 
    R[1][1] += a2[i]*v2[i] 
    R[1][2] += a3[i]*v2[i] 
    R[2][2] += a3[i]*v3[i] 
print(R) # 행렬 R 출력

[[1.41421356 1.41421356 0.70710678]
 [0.         1.73205081 0.        ]
 [0.         0.         1.22474487]]


## 넘파이로 간단히 계산 실습

In [60]:
# 기본 내적
print(np.inner(a,b))

# QR 분해
Q, R = np.linalg.qr(A)
print(Q)
print(R)

32
[[-0.70710678  0.57735027 -0.40824829]
 [-0.         -0.57735027 -0.81649658]
 [-0.70710678 -0.57735027  0.40824829]]
[[-1.41421356 -1.41421356 -0.70710678]
 [ 0.         -1.73205081  0.        ]
 [ 0.          0.         -1.22474487]]
